# Imagen base ligera de Node.js
FROM node:20-alpine

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Puerto donde corre tu app
EXPOSE 3000

# Comando para iniciar la app (SvelteKit en modo dev o prod)
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
